[services.Backend]
  command = "cd Backend && npm install"
  start = "cd Backend && npm run start"

[services.Frontend]
  command = "cd Frontend && npm install && npm run build"
  start = "cd Frontend && npm start"
