[services.backend]
  command = "cd backend && npm install --omit=dev"
  start = "cd backend && npm run start"


[services.frontend]
  command = "cd frontend && npm install && npm run build"
  start = "cd frontend && npm start"
