# For the backend service
[services.backend]
  command = "cd backend && npm install"
  start = "cd backend && npm start"

# For the frontend service (React)
[services.frontend]
  command = "cd frontend && npm install && npm run build"
  start = "cd frontend && npm start"
