[services.backend]
  command = "cd Backend && echo 'Installing dependencies...' && npm install --omit=dev"
  start = "cd Backend && echo 'Starting backend...' && npm run start"

[services.frontend]
  command = "cd Frontend && echo 'Installing frontend dependencies...' && npm install && npm run build"
  start = "cd Frontend && echo 'Starting frontend...' && npm start"
