[services.backend]
command = "cd Backend && rm -rf node_modules && npm install && echo 'Installing dependencies complete' && npx prisma generate && echo 'Prisma Client generated successfully'"
start = "cd Backend && npm run start"


[services.frontend]
command = "cd Frontend && npm install && npm run build" 
start = "cd Frontend && npm start"
