# For the backend service
[services.backend]
  command = "cd backend && npm install && npm run build"
  start = "cd backend && npm start"

# For the frontend service (if using a static React site)
[services.frontend]
  command = "cd frontend && npm install && npm run build"
  start = "cd frontend && npm run serve"